package Vista;

import Conexion.ConexionBD;
import java.sql.*;
import java.util.logging.*;
import javax.swing.JInternalFrame;
import javax.swing.table.DefaultTableModel;


public class BuscarComprobante extends javax.swing.JInternalFrame {

    int nums = 0;
    String accion;
    DefaultTableModel modelo;

    /**
     * Creates new form ClientesB
     */
    public BuscarComprobante() {
        initComponents();
        mostrarclientes("");
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        mnenviar = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbComprobante = new rojerusan.RSTableMetro();
        btnAgregar = new javax.swing.JButton();
        btnCancelar1 = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();

        mnenviar.setText("Enviar Datos");
        mnenviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnenviarActionPerformed(evt);
            }
        });
        jPopupMenu1.add(mnenviar);

        setBackground(new java.awt.Color(251, 248, 248));
        setClosable(true);
        setIconifiable(true);
        setPreferredSize(new java.awt.Dimension(325, 300));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(251, 248, 248));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buscar Tipo de Comprobante:", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(0, 0, 102))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbComprobante.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        tbComprobante.setAltoHead(20);
        tbComprobante.setColorBackgoundHead(new java.awt.Color(0, 102, 102));
        tbComprobante.setColorFilasBackgound2(new java.awt.Color(240, 240, 240));
        tbComprobante.setColorFilasForeground1(new java.awt.Color(51, 51, 51));
        tbComprobante.setColorFilasForeground2(new java.awt.Color(51, 51, 51));
        tbComprobante.setFuenteFilas(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        tbComprobante.setFuenteFilasSelect(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tbComprobante.setFuenteHead(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tbComprobante.setGrosorBordeFilas(0);
        tbComprobante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbComprobanteMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbComprobante);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 27, 298, 162));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 11, 307, 199);

        btnAgregar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/comp5.png"))); // NOI18N
        btnAgregar.setText("Nuevo");
        btnAgregar.setContentAreaFilled(false);
        btnAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregar.setFocusPainted(false);
        btnAgregar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAgregar.setIconTextGap(0);
        btnAgregar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/comp6.png"))); // NOI18N
        btnAgregar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar);
        btnAgregar.setBounds(-10, 210, 67, 38);

        btnCancelar1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCancelar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/comp1.png"))); // NOI18N
        btnCancelar1.setText("Cancelar");
        btnCancelar1.setContentAreaFilled(false);
        btnCancelar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar1.setFocusPainted(false);
        btnCancelar1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCancelar1.setIconTextGap(0);
        btnCancelar1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/comp2.png"))); // NOI18N
        btnCancelar1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar1);
        btnCancelar1.setBounds(50, 210, 81, 40);

        btnRegresar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/comp3.png"))); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.setContentAreaFilled(false);
        btnRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresar.setFocusPainted(false);
        btnRegresar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRegresar.setIconTextGap(0);
        btnRegresar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/comp4.png"))); // NOI18N
        btnRegresar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar);
        btnRegresar.setBounds(230, 210, 84, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void mnenviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnenviarActionPerformed

}//GEN-LAST:event_mnenviarActionPerformed

    private void tbComprobanteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbComprobanteMouseClicked
      int row = tbComprobante.getSelectedRow();
        Ventas.txtComprobante.setText(tbComprobante.getValueAt(row, 1).toString());
        Ventas.txtIdComprobante.setText(tbComprobante.getValueAt(row, 0).toString());
        
    }//GEN-LAST:event_tbComprobanteMouseClicked

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnCancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelar1ActionPerformed
         Ventas.txtComprobante.setText("");
        btnRegresar.requestFocus();
    }//GEN-LAST:event_btnCancelar1ActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
      frmComprobante cli = new frmComprobante();
        CentrarVentana(cli);
    }//GEN-LAST:event_btnAgregarActionPerformed
    public void CentrarVentana(JInternalFrame internalFrame) {
        int x = (frmPrincipal.tbn_escritorio.getWidth() / 2) - internalFrame.getWidth() / 2;
        int y = (frmPrincipal.tbn_escritorio.getHeight() / 2) - internalFrame.getHeight() / 2;
        if (internalFrame.isShowing()) {
            internalFrame.setLocation(x, y);
        } else {
            frmPrincipal.tbn_escritorio.add(internalFrame);
            internalFrame.setLocation(x, y);
            internalFrame.show();
        }
    }   
    void mostrarclientes(String buscar) {
        String[] titulos = {"Id", "Descripción", "Estado"};
        String[] Registros = new String[3];
        modelo = new DefaultTableModel(null, titulos);
        String Sql = "SELECT * FROM tipoComprobante WHERE Estado = 'Activo'";

        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(Sql);
            while (rs.next()) {
                Registros[0] = rs.getString("IdTipoComprobante");
                Registros[1] = rs.getString("Descripcion");
                Registros[2] = rs.getString("Estado");
                modelo.addRow(Registros);
            }
            tbComprobante.setModel(modelo);
        } catch (SQLException ex) {
            Logger.getLogger(BuscarComprobante.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCancelar1;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenuItem mnenviar;
    private rojerusan.RSTableMetro tbComprobante;
    // End of variables declaration//GEN-END:variables
ConexionBD cc = new ConexionBD();
    Connection cn = cc.conectar();
}
