package Vista;

import Conexion.ConexionBD;
import java.sql.*;
import java.util.logging.*;
import javax.swing.table.DefaultTableModel;
import static Vista.frmCompras.*;


public class BuscarProveedor extends javax.swing.JInternalFrame {

    int nums = 0;

    DefaultTableModel modelo;

    /**
     * Creates new form ClientesB
     */
    public BuscarProveedor() {
        initComponents();
        mostrarProveedor("");
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        mnenviar = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbProveedor = new rojerusan.RSTableMetro();
        txtBuscar = new jtextfieldround.JTextFieldRound();
        btnbus1 = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        btnCancelar1 = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();

        mnenviar.setText("Enviar Datos");
        mnenviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnenviarActionPerformed(evt);
            }
        });
        jPopupMenu1.add(mnenviar);

        setBackground(new java.awt.Color(251, 248, 248));
        setClosable(true);
        setIconifiable(true);

        jPanel1.setBackground(new java.awt.Color(251, 248, 248));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Buscar Proveedor:", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 2, 11), new java.awt.Color(0, 102, 102))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Buscar:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        tbProveedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        tbProveedor.setAltoHead(20);
        tbProveedor.setColorBackgoundHead(new java.awt.Color(0, 102, 102));
        tbProveedor.setColorFilasBackgound2(new java.awt.Color(240, 240, 240));
        tbProveedor.setColorFilasForeground1(new java.awt.Color(51, 51, 51));
        tbProveedor.setColorFilasForeground2(new java.awt.Color(51, 51, 51));
        tbProveedor.setFuenteFilas(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        tbProveedor.setFuenteFilasSelect(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tbProveedor.setFuenteHead(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tbProveedor.setGrosorBordeFilas(0);
        tbProveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbProveedorMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbProveedor);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 61, 358, 158));

        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });
        jPanel1.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 160, -1));

        btnbus1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnbus1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/tod1.png"))); // NOI18N
        btnbus1.setText("Todo");
        btnbus1.setContentAreaFilled(false);
        btnbus1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnbus1.setFocusPainted(false);
        btnbus1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/tod2.png"))); // NOI18N
        btnbus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbus1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnbus1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));

        btnAgregar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/n1.png"))); // NOI18N
        btnAgregar.setText("Registrar");
        btnAgregar.setContentAreaFilled(false);
        btnAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregar.setFocusPainted(false);
        btnAgregar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAgregar.setIconTextGap(0);
        btnAgregar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/n2.png"))); // NOI18N
        btnAgregar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnCancelar1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCancelar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/can1.png"))); // NOI18N
        btnCancelar1.setText("Cancelar");
        btnCancelar1.setContentAreaFilled(false);
        btnCancelar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar1.setFocusPainted(false);
        btnCancelar1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCancelar1.setIconTextGap(0);
        btnCancelar1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/can2.png"))); // NOI18N
        btnCancelar1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelar1ActionPerformed(evt);
            }
        });

        btnRegresar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/vo1.png"))); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.setContentAreaFilled(false);
        btnRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresar.setFocusPainted(false);
        btnRegresar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRegresar.setIconTextGap(0);
        btnRegresar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/vo2.png"))); // NOI18N
        btnRegresar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAgregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar1)
                        .addGap(115, 115, 115)
                        .addComponent(btnRegresar))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnRegresar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void mnenviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnenviarActionPerformed

}//GEN-LAST:event_mnenviarActionPerformed

    private void tbProveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbProveedorMouseClicked
        int row = tbProveedor.getSelectedRow();
        txtIdProveedor.setText(tbProveedor.getValueAt(row, 0).toString());
        txtNombreProveedor.setText(tbProveedor.getValueAt(row, 1).toString());
        txtRuc.setText(tbProveedor.getValueAt(row, 2).toString());

    }//GEN-LAST:event_tbProveedorMouseClicked

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        mostrarProveedor(txtBuscar.getText());
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void btnbus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbus1ActionPerformed
        // TODO add your handling code here:
        mostrarProveedor("");
        txtBuscar.setText("");
    }//GEN-LAST:event_btnbus1ActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
         dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnCancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelar1ActionPerformed
       txtNombreProveedor.setText("");
        txtRuc.setText("");
        txtNombreProveedor.requestFocus();
    }//GEN-LAST:event_btnCancelar1ActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        frmProveedor cli = new frmProveedor();
    frmPrincipal.tbn_escritorio.add(cli);
    cli.toFront();
    cli.setVisible(true);
    }//GEN-LAST:event_btnAgregarActionPerformed
       void mostrarProveedor(String buscar) {
        String[] titulos = {"ID", "Nombre", "Ruc"};
        String Sql = "SELECT * FROM proveedor WHERE Estado='Activo' AND CONCAT(Nombre,Ruc) LIKE '%" + buscar + "%'";
        modelo = new DefaultTableModel(null, titulos);
        String[] Registros = new String[3];
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(Sql);
            while (rs.next()) {
                Registros[0] = rs.getString("IdProveedor");
                Registros[1] = rs.getString("Nombre");
                Registros[2] = rs.getString("Ruc");
                modelo.addRow(Registros);
            }
            tbProveedor.setModel(modelo);
        } catch (SQLException ex) {
            Logger.getLogger(BuscarClientes.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCancelar1;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnbus1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenuItem mnenviar;
    private rojerusan.RSTableMetro tbProveedor;
    private jtextfieldround.JTextFieldRound txtBuscar;
    // End of variables declaration//GEN-END:variables
ConexionBD cc = new ConexionBD();
    Connection cn = cc.conectar();
}
