
package Vista;

import Conexion.ConexionBD;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;


public class ConsultasEmpleados extends javax.swing.JInternalFrame {
 
    public ConsultasEmpleados() {
        initComponents();
        txtDni.setEnabled(false);
        txtEspecialidad.setEnabled(false);
        CargarlistaEmpleados();
    }
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        rdgenero = new javax.swing.JRadioButton();
        rddni = new javax.swing.JRadioButton();
        rdtodo = new javax.swing.JRadioButton();
        cbogenero = new javax.swing.JComboBox();
        btnbuscar = new javax.swing.JButton();
        rdEspecialidad = new javax.swing.JRadioButton();
        txtDni = new jtextfieldround.JTextFieldRound();
        txtEspecialidad = new jtextfieldround.JTextFieldRound();
        jLabel1 = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();
        txtCantidad = new jtextfieldround.JTextFieldRound();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbclientes = new rojerusan.RSTableMetro();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setTitle("Consultar Empleados");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Buscar Empleado:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 11), new java.awt.Color(0, 102, 0))); // NOI18N

        buttonGroup1.add(rdgenero);
        rdgenero.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rdgenero.setForeground(new java.awt.Color(0, 102, 51));
        rdgenero.setSelected(true);
        rdgenero.setText("Mostrar Empleados por Genero:");
        rdgenero.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rdgenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdgeneroActionPerformed(evt);
            }
        });

        buttonGroup1.add(rddni);
        rddni.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rddni.setForeground(new java.awt.Color(0, 102, 51));
        rddni.setText("Buscar Empleados  por DNI:");
        rddni.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rddni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rddniActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdtodo);
        rdtodo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rdtodo.setForeground(new java.awt.Color(0, 102, 51));
        rdtodo.setText("Mostrar todos los Empleados");
        rdtodo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rdtodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdtodoActionPerformed(evt);
            }
        });

        cbogenero.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "⠀⠀⠀", "M", "F" }));
        cbogenero.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cbogenero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbogeneroKeyPressed(evt);
            }
        });

        btnbuscar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnbuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/btn31.png"))); // NOI18N
        btnbuscar.setContentAreaFilled(false);
        btnbuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnbuscar.setFocusPainted(false);
        btnbuscar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/btn30.png"))); // NOI18N
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdEspecialidad);
        rdEspecialidad.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rdEspecialidad.setForeground(new java.awt.Color(0, 102, 51));
        rdEspecialidad.setText("Buscar Empleados por Especialidad :");
        rdEspecialidad.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rdEspecialidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdEspecialidadActionPerformed(evt);
            }
        });

        txtDni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDniKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdgenero)
                            .addComponent(rddni)
                            .addComponent(rdtodo))
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(rdEspecialidad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(cbogenero, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnbuscar)
                .addContainerGap(273, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(rddni))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rdgenero)
                                    .addComponent(cbogenero, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rdEspecialidad))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rdtodo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(btnbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 51));
        jLabel1.setText("Cantidad de Registros:");

        btnCerrar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/btn28.png"))); // NOI18N
        btnCerrar.setContentAreaFilled(false);
        btnCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrar.setFocusPainted(false);
        btnCerrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/btn29.png"))); // NOI18N
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        txtCantidad.setEditable(false);

        tbclientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbclientes.setAltoHead(22);
        tbclientes.setColorBackgoundHead(new java.awt.Color(0, 51, 51));
        tbclientes.setColorFilasBackgound2(new java.awt.Color(240, 240, 240));
        tbclientes.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        tbclientes.setColorFilasForeground2(new java.awt.Color(0, 0, 0));
        tbclientes.setFuenteFilas(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        tbclientes.setFuenteFilasSelect(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tbclientes.setFuenteHead(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        tbclientes.setGrosorBordeFilas(0);
        jScrollPane2.setViewportView(tbclientes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(4, 4, 4)
                        .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(248, 248, 248)
                        .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(btnCerrar)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void rdgeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdgeneroActionPerformed
// TODO add your handling code here:
    if(rdgenero.isSelected()==true)
    {
        cbogenero.requestFocus();
        cbogenero.setSelectedItem(0);
        cbogenero.setEnabled(true);
        txtDni.setEnabled(false);
        txtDni.setText("");
        txtEspecialidad.setEnabled(false);
        txtEspecialidad.setText("");
        btnbuscar.setEnabled(true);
        CargarlistaEmpleados();
        
    }
}//GEN-LAST:event_rdgeneroActionPerformed

private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
   

// TODO add your handling code here:
   String sexo= cbogenero.getSelectedItem().toString();
   String dni=txtDni.getText();
   String especialidad=txtEspecialidad.getText();
   
   if(rdgenero.isSelected()==true)
   {
       DefaultTableModel modelo= new DefaultTableModel();
         String[] Titulos = {"Id", "Nombres", "Apellidos", "Especialidad", "Sexo", "DNI", "Email", "Teléfono", "Dirección", "Ingreso", "Salida", "Sueldo"};
       modelo.setColumnIdentifiers(Titulos);
       this.tbclientes.setModel(modelo);
       try {
            
            String ConsultaSQL="SELECT * FROM empleado WHERE Sexo='"+sexo+"'";
        
            String []registros= new String[12];
           
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(ConsultaSQL);
            while(rs.next())
            {
                registros[0] = rs.getString("idEmpleado");
                registros[1] = rs.getString("Nombres");
                registros[2] = rs.getString("Apellidos");
                registros[3] = rs.getString("Especialidad");
                registros[4] = rs.getString("Sexo");
                registros[5] = rs.getString("Dni");
                registros[6] = rs.getString("Email");
                registros[7] = rs.getString("Telefono");
                registros[8] = rs.getString("Direccion");
                registros[9] = rs.getString("HoraIngreso");
                registros[10] = rs.getString("HoraSalida");
                registros[11] = rs.getString("Sueldo");
                modelo.addRow(registros);
                                
            }
            tbclientes.setModel(modelo);
            txtCantidad.setText(""+tbclientes.getRowCount());
        } catch (SQLException ex) {
            Logger.getLogger(ConsultasEmpleados.class.getName()).log(Level.SEVERE, null, ex);
        }
   }
   
   if(rddni.isSelected()==true)
   {
       DefaultTableModel modelo= new DefaultTableModel();
         String[] Titulos = {"Id", "Nombres", "Apellidos", "Especialidad", "Sexo", "DNI", "Email", "Teléfono", "Dirección", "Ingreso", "Salida", "Sueldo"};
       modelo.setColumnIdentifiers(Titulos);
       this.tbclientes.setModel(modelo);
       try {
            
            String ConsultaSQL="SELECT * FROM empleado WHERE DNI='"+dni+"'";
        
            String []registros= new String[12];
           
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(ConsultaSQL);
            while(rs.next())
            {
                registros[0] = rs.getString("IdEmpleado");
                registros[1] = rs.getString("Nombres");
                registros[2] = rs.getString("Apellidos");
                registros[3] = rs.getString("Especialidad");
                registros[4] = rs.getString("Sexo");
                registros[5] = rs.getString("DNI");
                registros[6] = rs.getString("Email");
                registros[7] = rs.getString("Telefono");
                registros[8] = rs.getString("Direccion");
                registros[9] = rs.getString("HoraIngreso");
                registros[10] = rs.getString("HoraSalida");
                registros[11] = rs.getString("Sueldo");
                modelo.addRow(registros);
                                
            }
            tbclientes.setModel(modelo);
            txtCantidad.setText(""+tbclientes.getRowCount());
        } catch (SQLException ex) {
            Logger.getLogger(ConsultasEmpleados.class.getName()).log(Level.SEVERE, null, ex);
        }
       
       
   }
   
    if(rdEspecialidad.isSelected()==true)
   {
       DefaultTableModel modelo= new DefaultTableModel();
         String[] Titulos = {"Id", "Nombres", "Apellidos", "Especialidad", "Sexo", "DNI", "Email", "Teléfono", "Dirección", "Ingreso", "Salida", "Sueldo"};
       modelo.setColumnIdentifiers(Titulos);
       this.tbclientes.setModel(modelo);
       try {
            
            String ConsultaSQL="SELECT * FROM empleado WHERE Especialidad='"+especialidad+"'";
        
            String []registros= new String[12];
           
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(ConsultaSQL);
            while(rs.next())
            {
                registros[0] = rs.getString("IdEmpleado");
                registros[1] = rs.getString("Nombres");
                registros[2] = rs.getString("Apellidos");
                registros[3] = rs.getString("Especialidad");
                registros[4] = rs.getString("Sexo");
                registros[5] = rs.getString("DNI");
                registros[6] = rs.getString("Email");
                registros[7] = rs.getString("Telefono");
                registros[8] = rs.getString("Direccion");
                registros[9] = rs.getString("HoraIngreso");
                registros[10] = rs.getString("HoraSalida");
                registros[11] = rs.getString("Sueldo");
                modelo.addRow(registros);
                                
            }
            tbclientes.setModel(modelo);
            txtCantidad.setText(""+tbclientes.getRowCount());
        } catch (SQLException ex) {
            Logger.getLogger(ConsultasEmpleados.class.getName()).log(Level.SEVERE, null, ex);
        }
       
       
   }
   
   if(rdtodo.isSelected()==true)
   {
      CargarlistaEmpleados();
   }
    
}//GEN-LAST:event_btnbuscarActionPerformed

private void rddniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rddniActionPerformed
// TODO add your handling code here:
    if(rddni.isSelected()==true)
    {
        cbogenero.setSelectedIndex(0);
        cbogenero.setEnabled(false);
        txtDni.setEnabled(true);
        txtDni.requestFocus();
        txtEspecialidad.setText("");
        txtEspecialidad.setEnabled(false);
        btnbuscar.setEnabled(true);
        CargarlistaEmpleados();
    }
}//GEN-LAST:event_rddniActionPerformed

private void rdtodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdtodoActionPerformed
// TODO add your handling code here:
   CargarlistaEmpleados();
    cbogenero.setSelectedIndex(0);
    cbogenero.setEnabled(false);
    txtDni.setText("");
    txtDni.setEnabled(false);
    txtEspecialidad.setEnabled(false);
    txtEspecialidad.setText("");
    btnbuscar.setEnabled(false);
}//GEN-LAST:event_rdtodoActionPerformed

    private void cbogeneroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbogeneroKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            btnbuscar.requestFocus();

        }
    }//GEN-LAST:event_cbogeneroKeyPressed

    private void rdEspecialidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdEspecialidadActionPerformed
        if(rdEspecialidad.isSelected()==true)
    {
        cbogenero.setSelectedIndex(0);
        cbogenero.setEnabled(false);
        txtDni.setEnabled(false);
        txtDni.setText("");
        txtEspecialidad.setEnabled(true);
        txtEspecialidad.requestFocus();
        btnbuscar.setEnabled(true);
        CargarlistaEmpleados();
    }
    }//GEN-LAST:event_rdEspecialidadActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void txtDniKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDniKeyTyped
         char car = evt.getKeyChar();
        if ((car < '0' || car > '9')) {
            evt.consume();
        }
        int i = txtDni.getText().length();
        if (txtDni.getText().trim().length() < 8) {

        } else {
            i = 10;
            String com = txtDni.getText().substring(0, 7);
            txtDni.setText("");
            txtDni.setText(com);
        }
    }//GEN-LAST:event_txtDniKeyTyped

    void CargarlistaEmpleados()          
    {
        DefaultTableModel modelo= new DefaultTableModel();
         String[] Titulos = {"Id", "Nombres", "Apellidos", "Especialidad", "Sexo", "DNI", "Email", "Teléfono", "Dirección", "Ingreso", "Salida", "Sueldo"};
       modelo.setColumnIdentifiers(Titulos);
         this.tbclientes.setModel(modelo);
        try {
            
            String ConsultaSQL="SELECT * FROM empleado";
        
            String []registros= new String[12];
           
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(ConsultaSQL);
            while(rs.next())
            {
                registros[0] = rs.getString("IdEmpleado");
                registros[1] = rs.getString("Nombres");
                registros[2] = rs.getString("Apellidos");
                registros[3] = rs.getString("Especialidad");
                registros[4] = rs.getString("Sexo");
                registros[5] = rs.getString("DNI");
                registros[6] = rs.getString("Email");
                registros[7] = rs.getString("Telefono");
                registros[8] = rs.getString("Direccion");
                registros[9] = rs.getString("HoraIngreso");
                registros[10] = rs.getString("HoraSalida");
                registros[11] = rs.getString("Sueldo");
                modelo.addRow(registros);
                                
            }
            tbclientes.setModel(modelo);
            txtCantidad.setText(""+tbclientes.getRowCount());
        } catch (SQLException ex) {
            Logger.getLogger(ConsultasEmpleados.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnbuscar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox cbogenero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rdEspecialidad;
    private javax.swing.JRadioButton rddni;
    private javax.swing.JRadioButton rdgenero;
    private javax.swing.JRadioButton rdtodo;
    private rojerusan.RSTableMetro tbclientes;
    private jtextfieldround.JTextFieldRound txtCantidad;
    private jtextfieldround.JTextFieldRound txtDni;
    private jtextfieldround.JTextFieldRound txtEspecialidad;
    // End of variables declaration//GEN-END:variables
ConexionBD cc= new ConexionBD();
Connection cn = cc.conectar();


}
