
package Vista;

import Conexion.ConexionBD;
import Metodos.Metodos_Productos;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.ResultSet;
import java.util.Date;
import javax.swing.table.DefaultTableModel;
import javax.swing.JInternalFrame;

public class frmProductos extends javax.swing.JInternalFrame {

    
    private final Metodos_Productos CP = new Metodos_Productos();
    int num = 0;

    static ResultSet rs=null;
    DefaultTableModel dtm=new DefaultTableModel();

    String criterio,busqueda,Total;
    DefaultTableModel model;
    
    public frmProductos() {
        
        
        initComponents();
//        btnEliminar.setVisible(false);
        rbtDescripcion.setVisible(false);
        listar();
    }

    Metodos_Productos metodos = new Metodos_Productos();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
  
    private void listar() {
        jtb_datos.setModel(CP.getDatos());
    }

    //LIMPIAR TODOS LOS CAMPOS 
    //*********************************
    private void limpiar() {
        txtDescripcion.setText("");
        txtCosto.setText("");
        txtPrecio.setText("");
        txtPresentacion.setText("");
        chbEstado.setSelected(false);
        txtLaboratorio.setText("");
        txtConcentracion.setText("");
        txtSanitario.setText("");
        txtStock.setText("");
        txtDescripcion.requestFocus();
    }

    //*********************************
   
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        chbEstado = new javax.swing.JCheckBox();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jdtFecha = new com.toedter.calendar.JDateChooser();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        btnPresentacion = new javax.swing.JButton();
        btnLaboratorio = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        txtId = new jtextfieldround.JTextFieldRound();
        txtDescripcion = new jtextfieldround.JTextFieldRound();
        txtPresentacion = new jtextfieldround.JTextFieldRound();
        txtConcentracion = new jtextfieldround.JTextFieldRound();
        txtStock = new jtextfieldround.JTextFieldRound();
        txtCosto = new jtextfieldround.JTextFieldRound();
        txtPrecio = new jtextfieldround.JTextFieldRound();
        txtLaboratorio = new jtextfieldround.JTextFieldRound();
        txtSanitario = new jtextfieldround.JTextFieldRound();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnMostrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtb_datos = new javax.swing.JTable();
        txtIdPresentacion = new javax.swing.JTextField();
        txtIdLaboratorio = new javax.swing.JTextField();
        rbtDescripcion = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        btnGuardad = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jbt_limpiar = new javax.swing.JButton();
        btnReporte = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        txtBuscar = new jtextfieldround.JTextFieldRound();

        setClosable(true);
        setIconifiable(true);
        setPreferredSize(new java.awt.Dimension(1110, 705));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Registro de Productos");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, -1, -1));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1577, 54);

        jPanel2.setBackground(new java.awt.Color(251, 248, 248));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos del Producto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 2, 11), new java.awt.Color(0, 102, 102))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 51));
        jLabel2.setText("ID:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 19, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 51));
        jLabel3.setText("Descripción:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 51));
        jLabel4.setText("Presentación:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 51));
        jLabel6.setText("Concentración:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 150, 100, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 51));
        jLabel7.setText(" Precio de venta:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 100, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 51));
        jLabel8.setText("Estado:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        chbEstado.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        chbEstado.setForeground(new java.awt.Color(0, 102, 102));
        chbEstado.setText("Activo");
        chbEstado.setContentAreaFilled(false);
        chbEstado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        chbEstado.setFocusPainted(false);
        chbEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbEstadoActionPerformed(evt);
            }
        });
        chbEstado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                chbEstadoKeyPressed(evt);
            }
        });
        jPanel2.add(chbEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, -1, 30));

        jLabel15.setForeground(new java.awt.Color(0, 51, 51));
        jLabel15.setText("*");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 100, 14, -1));

        jLabel16.setForeground(new java.awt.Color(0, 51, 51));
        jLabel16.setText("*");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 140, 29, -1));

        jdtFecha.setDateFormatString("yyy/MM/dd ");
        jPanel2.add(jdtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 140, 160, 30));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 51, 51));
        jLabel19.setText("Fecha de Vencimiento:");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(696, 150, 130, -1));

        jLabel20.setForeground(new java.awt.Color(0, 51, 51));
        jLabel20.setText("*");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 140, 16, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 51, 51));
        jLabel21.setText("Costo:");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, 40, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 51, 51));
        jLabel23.setText("Laboratorio:");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 70, 80, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 51, 51));
        jLabel24.setText("Registro Sanitario:");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 110, 110, -1));

        jLabel26.setForeground(new java.awt.Color(0, 51, 51));
        jLabel26.setText("*");
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 30, -1));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 51, 51));
        jLabel27.setText("Stock:");
        jPanel2.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, -1, -1));

        jLabel28.setForeground(new java.awt.Color(0, 51, 51));
        jLabel28.setText("*");
        jPanel2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 60, 14, -1));

        btnPresentacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/btn46.png"))); // NOI18N
        btnPresentacion.setBorderPainted(false);
        btnPresentacion.setContentAreaFilled(false);
        btnPresentacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPresentacion.setFocusPainted(false);
        btnPresentacion.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/btn47.png"))); // NOI18N
        btnPresentacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPresentacionActionPerformed(evt);
            }
        });
        jPanel2.add(btnPresentacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 50, 50));

        btnLaboratorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/btn46.png"))); // NOI18N
        btnLaboratorio.setBorderPainted(false);
        btnLaboratorio.setContentAreaFilled(false);
        btnLaboratorio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLaboratorio.setFocusPainted(false);
        btnLaboratorio.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/btn47.png"))); // NOI18N
        btnLaboratorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLaboratorioActionPerformed(evt);
            }
        });
        jPanel2.add(btnLaboratorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 50, 50, 50));

        jLabel29.setForeground(new java.awt.Color(0, 51, 51));
        jLabel29.setText("*");
        jPanel2.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 60, 20, -1));

        jLabel30.setForeground(new java.awt.Color(0, 51, 51));
        jLabel30.setText("*");
        jPanel2.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 100, 23, -1));

        txtId.setEditable(false);
        txtId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIdKeyPressed(evt);
            }
        });
        jPanel2.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 90, 30));

        txtDescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDescripcionKeyPressed(evt);
            }
        });
        jPanel2.add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 190, 30));

        txtPresentacion.setEditable(false);
        txtPresentacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPresentacionKeyPressed(evt);
            }
        });
        jPanel2.add(txtPresentacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 150, 30));

        txtConcentracion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtConcentracionKeyPressed(evt);
            }
        });
        jPanel2.add(txtConcentracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 150, 30));

        txtStock.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtStockKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtStockKeyPressed(evt);
            }
        });
        jPanel2.add(txtStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, 120, 30));

        txtCosto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCostoKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCostoKeyPressed(evt);
            }
        });
        jPanel2.add(txtCosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, 120, 30));

        txtPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecioKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPrecioKeyPressed(evt);
            }
        });
        jPanel2.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, 120, 30));

        txtLaboratorio.setEditable(false);
        txtLaboratorio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLaboratorioKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtLaboratorioKeyPressed(evt);
            }
        });
        jPanel2.add(txtLaboratorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 60, 160, 30));

        txtSanitario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSanitarioKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSanitarioKeyPressed(evt);
            }
        });
        jPanel2.add(txtSanitario, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 100, 160, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 51, 51));
        jLabel14.setText(" * Campos Obligatorios");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 220, 120, -1));

        jLabel13.setForeground(new java.awt.Color(0, 51, 51));
        jLabel13.setText("*");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 20, 20));

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 60, 1080, 242);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 51));
        jLabel9.setText(" Buscar por Descripción:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 327, 134, 14);

        btnMostrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnMostrar.setForeground(new java.awt.Color(0, 0, 102));
        btnMostrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/button (14).png"))); // NOI18N
        btnMostrar.setBorder(null);
        btnMostrar.setBorderPainted(false);
        btnMostrar.setContentAreaFilled(false);
        btnMostrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMostrar.setFocusPainted(false);
        btnMostrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/button (15).png"))); // NOI18N
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnMostrar);
        btnMostrar.setBounds(370, 300, 170, 60);

        jtb_datos = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        jtb_datos.setBackground(new java.awt.Color(251, 248, 248));
        jtb_datos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jtb_datos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jtb_datos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtb_datosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtb_datos);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 365, 1080, 229);

        txtIdPresentacion.setEditable(false);
        txtIdPresentacion.setBorder(null);
        txtIdPresentacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdPresentacionActionPerformed(evt);
            }
        });
        getContentPane().add(txtIdPresentacion);
        txtIdPresentacion.setBounds(1167, 620, 60, 30);

        txtIdLaboratorio.setEditable(false);
        txtIdLaboratorio.setBorder(null);
        getContentPane().add(txtIdLaboratorio);
        txtIdLaboratorio.setBounds(1096, 637, 54, 14);

        rbtDescripcion.setSelected(true);
        rbtDescripcion.setText("Buscar por Desc.");
        rbtDescripcion.setBorder(null);
        rbtDescripcion.setContentAreaFilled(false);
        rbtDescripcion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(rbtDescripcion);
        rbtDescripcion.setBounds(0, 0, 99, 15);

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));
        jPanel3.setLayout(null);

        btnGuardad.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnGuardad.setForeground(new java.awt.Color(0, 0, 102));
        btnGuardad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/button (2).png"))); // NOI18N
        btnGuardad.setBorder(null);
        btnGuardad.setBorderPainted(false);
        btnGuardad.setContentAreaFilled(false);
        btnGuardad.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardad.setFocusPainted(false);
        btnGuardad.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/button (4).png"))); // NOI18N
        btnGuardad.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/button (4).png"))); // NOI18N
        btnGuardad.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/button (4).png"))); // NOI18N
        btnGuardad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardadActionPerformed(evt);
            }
        });
        btnGuardad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnGuardadKeyPressed(evt);
            }
        });
        jPanel3.add(btnGuardad);
        btnGuardad.setBounds(140, 0, 150, 70);

        btnEliminar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(0, 0, 102));
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/button (6).png"))); // NOI18N
        btnEliminar.setBorderPainted(false);
        btnEliminar.setContentAreaFilled(false);
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.setFocusPainted(false);
        btnEliminar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/button (5).png"))); // NOI18N
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel3.add(btnEliminar);
        btnEliminar.setBounds(440, 10, 140, 50);

        jbt_limpiar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbt_limpiar.setForeground(new java.awt.Color(0, 0, 102));
        jbt_limpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/button (8).png"))); // NOI18N
        jbt_limpiar.setBorderPainted(false);
        jbt_limpiar.setContentAreaFilled(false);
        jbt_limpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbt_limpiar.setFocusPainted(false);
        jbt_limpiar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/button (7).png"))); // NOI18N
        jbt_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_limpiarActionPerformed(evt);
            }
        });
        jPanel3.add(jbt_limpiar);
        jbt_limpiar.setBounds(10, 10, 130, 50);

        btnReporte.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnReporte.setForeground(new java.awt.Color(0, 0, 102));
        btnReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/button (9).png"))); // NOI18N
        btnReporte.setBorder(null);
        btnReporte.setBorderPainted(false);
        btnReporte.setContentAreaFilled(false);
        btnReporte.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReporte.setFocusPainted(false);
        btnReporte.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/button (10).png"))); // NOI18N
        btnReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteActionPerformed(evt);
            }
        });
        jPanel3.add(btnReporte);
        btnReporte.setBounds(290, 10, 150, 50);

        btnVolver.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(0, 0, 102));
        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/button (12).png"))); // NOI18N
        btnVolver.setBorderPainted(false);
        btnVolver.setContentAreaFilled(false);
        btnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVolver.setFocusPainted(false);
        btnVolver.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/button (11).png"))); // NOI18N
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jPanel3.add(btnVolver);
        btnVolver.setBounds(933, 10, 150, 50);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 600, 1110, 80);

        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });
        getContentPane().add(txtBuscar);
        txtBuscar.setBounds(150, 318, 210, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        listar();
        txtBuscar.setText("");
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void jtb_datosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtb_datosMouseClicked
        
        int row = jtb_datos.getSelectedRow();
                   // l.setBackground(new Color(203, 159, 41));
                   
        //        Date fec = jtb_datos.getValueAt(row, 7).toString();
        txtId.setText(jtb_datos.getValueAt(row, 0).toString());
        txtDescripcion.setText(jtb_datos.getValueAt(row, 2).toString());
        txtConcentracion.setText(jtb_datos.getValueAt(row, 3).toString());
        txtStock.setText(jtb_datos.getValueAt(row, 4).toString());
        txtCosto.setText(jtb_datos.getValueAt(row, 5).toString());
        txtPrecio.setText(jtb_datos.getValueAt(row, 6).toString());
        txtSanitario.setText(jtb_datos.getValueAt(row, 8).toString());
        //        jdtFecha.setDate(fec);

        //        jdtFecha.setText(7,((JTextField)frmProductos.jdtFecha.getDateEditor().getUiComponent()).getText());
        String est = jtb_datos.getValueAt(row, 10).toString();
        if (est.equals("Activo")) {
            chbEstado.setSelected(true);
        } else {
            chbEstado.setSelected(false);
        }
        num = 1;
    }//GEN-LAST:event_jtb_datosMouseClicked

    private void btnGuardadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardadActionPerformed
        double costo, precio;
//VALIDAR CAMPOS PARA QUE TODOS ESTEN LLENOS
        //--------------------------------------------------
        if (txtDescripcion.getText().isEmpty() || txtSanitario.getText().isEmpty() || txtStock.getText().isEmpty() || txtPresentacion.getText().isEmpty()
            || txtCosto.getText().isEmpty() || txtPrecio.getText().isEmpty() || txtLaboratorio.getText().isEmpty() || txtConcentracion.getText().isEmpty() ) {
            JOptionPane.showMessageDialog(this, "Por favor rellene todos los campos");
            //--------------------------------------------------
        } else {
            costo= Double.parseDouble(txtCosto.getText());
            precio= Double.parseDouble(txtPrecio.getText());
            
            if(costo > 0){
            if (precio > costo){
                
            String ID = txtId.getText();
            String Descripcion = txtDescripcion.getText();
            String Concentracion = txtConcentracion.getText();
            int Stock = Integer.parseInt(txtStock.getText());
            float Costo = Float.parseFloat(txtCosto.getText());
            float Precio = Float.parseFloat(txtPrecio.getText());
            String RegistroSanitario = txtSanitario.getText();
            
            Date Fecha = jdtFecha.getDate();
            Long d = Fecha.getTime();
            java.sql.Date fecha = new java.sql.Date(d);

            String Estado;
            if (chbEstado.isSelected()) {
                Estado = "Activo";
            } else {
                Estado = "Inactivo";
            }
            
            String Presentacion = txtIdPresentacion.getText();
            String Laboratorio = txtIdLaboratorio.getText();

            if (num == 0) {
                int respuesta = metodos.guardarProductos(Descripcion, Concentracion, Stock, Costo, Precio, RegistroSanitario, fecha, Estado, Presentacion, Laboratorio);
                if (respuesta > 0) {
                    listar();

                    limpiar();
                }
            }if (num != 0) {
                int respuesta = metodos.ActualizarDatos(ID, Descripcion, Concentracion, Stock, Costo, Precio, RegistroSanitario, fecha, Estado, Presentacion, Laboratorio);
                if (respuesta > 0) {
                    listar();
                    num = 0;
                }
            }
        } else{
                JOptionPane.showMessageDialog(null, "El precio de venta no puede ser menor o igual al costo del Producto");
            }
        }else{
               JOptionPane.showMessageDialog(null, "El costo del producto no puede ser menor o igual a 0"); 
            }
        }
    }//GEN-LAST:event_btnGuardadActionPerformed

    private void btnGuardadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnGuardadKeyPressed
           double costo, precio;
//VALIDAR CAMPOS PARA QUE TODOS ESTEN LLENOS
        //--------------------------------------------------
        if (txtDescripcion.getText().isEmpty() || txtSanitario.getText().isEmpty() || txtStock.getText().isEmpty() || txtPresentacion.getText().isEmpty()
            || txtCosto.getText().isEmpty() || txtPrecio.getText().isEmpty() || txtLaboratorio.getText().isEmpty() || txtConcentracion.getText().isEmpty() ) {
            JOptionPane.showMessageDialog(this, "Por favor rellene todos los campos");
            //--------------------------------------------------
        } else {
            costo= Double.parseDouble(txtCosto.getText());
            precio= Double.parseDouble(txtPrecio.getText());
            if (precio > costo){
                
            String ID = txtId.getText();
            String Descripcion = txtDescripcion.getText();
            String Concentracion = txtConcentracion.getText();
            int Stock = Integer.parseInt(txtStock.getText());
            float Costo = Float.parseFloat(txtCosto.getText());
            float Precio = Float.parseFloat(txtPrecio.getText());
            String RegistroSanitario = txtSanitario.getText();
            
            Date Fecha = jdtFecha.getDate();
            Long d = Fecha.getTime();
            java.sql.Date fecha = new java.sql.Date(d);

            String Estado;
            if (chbEstado.isSelected()) {
                Estado = "Activo";
            } else {
                Estado = "Inactivo";
            }
            
            String Presentacion = txtIdPresentacion.getText();
            String Laboratorio = txtIdLaboratorio.getText();

            if (num == 0) {
                int respuesta = metodos.guardarProductos(Descripcion, Concentracion, Stock, Costo, Precio, RegistroSanitario, fecha, Estado, Presentacion, Laboratorio);
                if (respuesta > 0) {
                    listar();

                    limpiar();
                }
            }if (num != 0) {
                int respuesta = metodos.ActualizarDatos(ID, Descripcion, Concentracion, Stock, Costo, Precio, RegistroSanitario, fecha, Estado, Presentacion, Laboratorio);
                if (respuesta > 0) {
                    listar();
                    num = 0;
                }
            }
        } else{
                JOptionPane.showMessageDialog(null, "El precio de venta no puede ser menor o igual al costo del Producto");
            }
        }
    }//GEN-LAST:event_btnGuardadKeyPressed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed

        int fila = jtb_datos.getSelectedRowCount();
        if (fila < 1) {
            JOptionPane.showMessageDialog(null, "Seleccione Un registro de la tabla");
        } else if(fila==1){
            int result = JOptionPane.showConfirmDialog(this, "¿Desea eliminar el registro?", "Mensaje del Sistema", JOptionPane.YES_NO_OPTION);
        if (result == JOptionPane.YES_OPTION) {
            if (CP.EliminarDatos(jtb_datos.getValueAt(jtb_datos.getSelectedRow(), 0).toString()) > 0) {
                limpiar();
                listar();
            }
        }if (result == JOptionPane.NO_OPTION) {
            JOptionPane.showMessageDialog(null, "Eliminación cancelada!");
            
        }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void jbt_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_limpiarActionPerformed
        
        txtId.setText("");
        txtDescripcion.setText("");
        txtCosto.setText("");
        txtPrecio.setText("");
        txtPresentacion.setText("");
        chbEstado.setSelected(false);
        txtLaboratorio.setText("");
        txtConcentracion.setText("");
        txtSanitario.setText("");
        txtStock.setText("");
        txtDescripcion.requestFocus();
    }//GEN-LAST:event_jbt_limpiarActionPerformed

    private void btnPresentacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPresentacionActionPerformed

        BuscarPresentacion Presentacion = new BuscarPresentacion();
        frmPrincipal.tbn_escritorio.add(Presentacion);
        Presentacion.toFront();
        Presentacion.setVisible(true);
    }//GEN-LAST:event_btnPresentacionActionPerformed

    private void btnLaboratorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaboratorioActionPerformed
        BuscarLaboratorio Laboratorio = new BuscarLaboratorio();
        frmPrincipal.tbn_escritorio.add(Laboratorio);
        Laboratorio.toFront();
        Laboratorio.setVisible(true);
    }//GEN-LAST:event_btnLaboratorioActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteActionPerformed
        JRReporte cr = new JRReporte();
        Connection con = null;
        try {
            con = ConexionBD.conectar();
            String ruta = System.getProperty("user.dir") + "\\src\\Reportes\\Productos.jrxml"; 
            cr.abrirReporte(ruta, con);
            con.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_btnReporteActionPerformed

    private void chbEstadoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_chbEstadoKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            btnGuardad.requestFocus();

        }
    }//GEN-LAST:event_chbEstadoKeyPressed

    private void chbEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chbEstadoActionPerformed

    private void txtIdPresentacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdPresentacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdPresentacionActionPerformed

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
       BuscarProductos();
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void txtIdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            txtDescripcion.requestFocus();

        }
    }//GEN-LAST:event_txtIdKeyPressed

    private void txtDescripcionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescripcionKeyPressed
     if (evt.getKeyCode() == evt.VK_ENTER) {
            txtPresentacion.requestFocus();

        }
    }//GEN-LAST:event_txtDescripcionKeyPressed

    private void txtPresentacionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPresentacionKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPresentacionKeyPressed

    private void txtConcentracionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtConcentracionKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConcentracionKeyPressed

    private void txtStockKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStockKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStockKeyPressed

    private void txtCostoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCostoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCostoKeyPressed

    private void txtCostoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCostoKeyTyped
        char c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            getToolkit().beep();
            evt.consume();

            JOptionPane.showMessageDialog(null, "Ingrese solo Números");
        }
    }//GEN-LAST:event_txtCostoKeyTyped

    private void txtPrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioKeyTyped
       char c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            getToolkit().beep();
            evt.consume();

            JOptionPane.showMessageDialog(null, "Ingrese solo Números");
        }
    }//GEN-LAST:event_txtPrecioKeyTyped

    private void txtPrecioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioKeyPressed

    private void txtLaboratorioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLaboratorioKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLaboratorioKeyTyped

    private void txtLaboratorioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLaboratorioKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLaboratorioKeyPressed

    private void txtSanitarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSanitarioKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSanitarioKeyTyped

    private void txtSanitarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSanitarioKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSanitarioKeyPressed

    private void txtStockKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStockKeyTyped
        char car = evt.getKeyChar();
        if ((car < '0' || car > '9')) {
            evt.consume();
        }
        
    }//GEN-LAST:event_txtStockKeyTyped

     public void CentrarVentanaUsuario(JInternalFrame internalFrame) {
        int x = (frmPrincipal.tbn_escritorio.getWidth() / 2) - internalFrame.getWidth() / 2;
        int y = (frmPrincipal.tbn_escritorio.getHeight() / 2) - internalFrame.getHeight() / 2;
        if (internalFrame.isShowing()) {
            internalFrame.setLocation(x, y);
        } else {
            frmPrincipal.tbn_escritorio.add(internalFrame);
            internalFrame.setLocation(x, y);
            internalFrame.show();
        }
    }
        
          //METODO PARA BUSCAR REGISTROS
    //-------------------------------------------------------------------------------------------------------------------------------------------

   void BuscarProductos(){
        String titulos[]={"ID","Presentación","Descripción","Concentración","Stock","Costo","Venta","Vencimiento","Registro Sanitario","Laboratorio","Estado"};
        dtm.setColumnIdentifiers(titulos);
        
        Metodos_Productos categoria=new Metodos_Productos();
        busqueda=txtBuscar.getText();
        if(rbtDescripcion.isSelected()){
            criterio="Buscar";
        }
        try{
            rs=categoria.listarProductos(criterio,busqueda);
            boolean encuentra=false;
            String Datos[]=new String[11];
            int f,i;
            f=dtm.getRowCount();
            if(f>0){
                for(i=0;i<f;i++){
                    dtm.removeRow(0);
                }
            }
            while(rs.next()){
                Datos[0]=(String) rs.getString(1);
                Datos[1]=(String) rs.getString(2);
                Datos[2]=(String) rs.getString(3);
                Datos[3]=(String) rs.getString(4);
                Datos[4]=(String) rs.getString(5);
                Datos[5]=(String) rs.getString(6);
                Datos[6]=(String) rs.getString(7);
                Datos[7]=(String) rs.getString(8);
                Datos[8]=(String) rs.getString(9);
                Datos[9]=(String) rs.getString(10);
                Datos[10]=(String) rs.getString(11);

                dtm.addRow(Datos);
                encuentra=true;

            }
            if(encuentra=false){
                JOptionPane.showMessageDialog(null, "¡No se encuentra!");
            }

        }catch(Exception ex){
            ex.printStackTrace();
        }
        jtb_datos.setModel(dtm);
    }
    //-------------------------------------------------------------------------------------------------------------------------------------------


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardad;
    private javax.swing.JButton btnLaboratorio;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JButton btnPresentacion;
    public static javax.swing.JButton btnReporte;
    private javax.swing.JButton btnVolver;
    private javax.swing.JCheckBox chbEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbt_limpiar;
    public static com.toedter.calendar.JDateChooser jdtFecha;
    private javax.swing.JTable jtb_datos;
    private javax.swing.JRadioButton rbtDescripcion;
    private jtextfieldround.JTextFieldRound txtBuscar;
    private jtextfieldround.JTextFieldRound txtConcentracion;
    private jtextfieldround.JTextFieldRound txtCosto;
    private jtextfieldround.JTextFieldRound txtDescripcion;
    private jtextfieldround.JTextFieldRound txtId;
    public static javax.swing.JTextField txtIdLaboratorio;
    public static javax.swing.JTextField txtIdPresentacion;
    public static jtextfieldround.JTextFieldRound txtLaboratorio;
    private jtextfieldround.JTextFieldRound txtPrecio;
    public static jtextfieldround.JTextFieldRound txtPresentacion;
    private jtextfieldround.JTextFieldRound txtSanitario;
    private jtextfieldround.JTextFieldRound txtStock;
    // End of variables declaration//GEN-END:variables
ConexionBD cc = new ConexionBD();
    Connection cn = cc.conectar();}
