package Vista;

import Metodos.Metodos_User;
import java.util.*;
import java.util.GregorianCalendar;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

public class frmPrincipal extends javax.swing.JFrame  implements Runnable{

    String hora, minutos, segundos;
    Thread hilo;
    private void cerrar() {
        String botones[] = {"Cerrar", "Cancelar"};
        int eleccion = JOptionPane.showOptionDialog(this, "¿Desea cerrar la aplicación?", "Salir de la aplicación!", 0, 0, null, botones, this);
        
        if (eleccion == JOptionPane.YES_OPTION) {
            System.exit(0);

        } else if (eleccion == JOptionPane.NO_OPTION) {

            JOptionPane.showMessageDialog(this, "Se cancelo el cierre");
        }
    }

    public frmPrincipal() {

        initComponents();
        hilo = new Thread(this);
        hilo.start();
        
        
    
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        this.setLocationRelativeTo(null);
    }
    Metodos_User metodos = new Metodos_User();
    
    public void hora(){
        
        Calendar calendario = new GregorianCalendar();
        Date horaActual = new Date();
        calendario.setTime(horaActual);
        hora=calendario.get(Calendar.HOUR_OF_DAY)>9?""+calendario.get(Calendar.HOUR_OF_DAY):"0"+calendario.get(Calendar.HOUR_OF_DAY);
        minutos=calendario.get(Calendar.MINUTE)>9?""+calendario.get(Calendar.MINUTE):"0"+calendario.get(Calendar.MINUTE);
        segundos=calendario.get(Calendar.SECOND)>9?""+calendario.get(Calendar.SECOND):"0"+calendario.get(Calendar.SECOND);
    }
    public void run(){
        Thread current=Thread.currentThread();
        
        while(current==hilo){
        hora();
        lblHora.setText(hora+":"+minutos+":"+segundos);
    }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem5 = new javax.swing.JMenuItem();
        jToggleButton1 = new javax.swing.JToggleButton();
        tbn_escritorio = new javax.swing.JDesktopPane();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        lblNombreUsuario = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblRol = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        btnNuevo = new javax.swing.JButton();
        btnCliente = new javax.swing.JButton();
        btnCaja = new javax.swing.JButton();
        btnVenta1 = new javax.swing.JButton();
        lblHora = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        mniEmpleado = new javax.swing.JMenuItem();
        mniEmpleado1 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        mnuComprobante = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mnuCompra = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem24 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem23 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jmuEmpleados = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jmuEmpleados1 = new javax.swing.JMenuItem();
        jMenuItem22 = new javax.swing.JMenuItem();
        mniReportes = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem21 = new javax.swing.JMenuItem();
        MnuAdministrador = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        mnuPerfil = new javax.swing.JMenu();
        mnuAdminPerfil = new javax.swing.JMenuItem();

        jMenuItem5.setText("jMenuItem5");

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mi Pequeño Angelito");
        setExtendedState(6);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        tbn_escritorio.setBackground(new java.awt.Color(0, 102, 102));

        kGradientPanel1.setkEndColor(new java.awt.Color(0, 153, 153));
        kGradientPanel1.setkStartColor(new java.awt.Color(0, 102, 204));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 51));
        jLabel1.setText("Usuario:");

        lblNombreUsuario.setFont(new java.awt.Font("AR JULIAN", 1, 14)); // NOI18N
        lblNombreUsuario.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 204, 51));
        jLabel2.setText("Rol:");

        lblRol.setFont(new java.awt.Font("AR JULIAN", 1, 14)); // NOI18N
        lblRol.setForeground(new java.awt.Color(255, 255, 255));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 204, 51));
        jLabel3.setText("Id:");

        lblId.setFont(new java.awt.Font("AR JULIAN", 1, 14)); // NOI18N
        lblId.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblRol, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblId, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(425, Short.MAX_VALUE))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblId, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(lblRol, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(lblNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/config-botton.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setFocusPainted(false);
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/cofig-botton.png"))); // NOI18N
        jButton2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/cofig-botton.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/perfil-botton_off.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusPainted(false);
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/perfil-botton.png"))); // NOI18N
        jButton1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/perfil-botton.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        kGradientPanel2.setBackground(new java.awt.Color(204, 204, 204));
        kGradientPanel2.setkEndColor(new java.awt.Color(240, 240, 240));
        kGradientPanel2.setkStartColor(new java.awt.Color(204, 204, 204));

        btnNuevo.setBackground(new java.awt.Color(255, 255, 255));
        btnNuevo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnNuevo.setForeground(new java.awt.Color(0, 51, 51));
        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/pa6.png"))); // NOI18N
        btnNuevo.setMnemonic('k');
        btnNuevo.setText("Productos");
        btnNuevo.setContentAreaFilled(false);
        btnNuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNuevo.setFocusPainted(false);
        btnNuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNuevo.setIconTextGap(0);
        btnNuevo.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/pa7.png"))); // NOI18N
        btnNuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnCliente.setBackground(new java.awt.Color(204, 255, 204));
        btnCliente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCliente.setForeground(new java.awt.Color(0, 51, 51));
        btnCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/pa5.png"))); // NOI18N
        btnCliente.setMnemonic('k');
        btnCliente.setText("Clientes ");
        btnCliente.setContentAreaFilled(false);
        btnCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCliente.setFocusPainted(false);
        btnCliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCliente.setIconTextGap(0);
        btnCliente.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Cl1.png"))); // NOI18N
        btnCliente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteActionPerformed(evt);
            }
        });

        btnCaja.setBackground(new java.awt.Color(204, 255, 204));
        btnCaja.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCaja.setForeground(new java.awt.Color(0, 51, 51));
        btnCaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/caj3.png"))); // NOI18N
        btnCaja.setMnemonic('k');
        btnCaja.setText("Caja");
        btnCaja.setContentAreaFilled(false);
        btnCaja.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCaja.setFocusPainted(false);
        btnCaja.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCaja.setIconTextGap(0);
        btnCaja.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/caj1.png"))); // NOI18N
        btnCaja.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCajaActionPerformed(evt);
            }
        });

        btnVenta1.setBackground(new java.awt.Color(204, 255, 204));
        btnVenta1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnVenta1.setForeground(new java.awt.Color(0, 51, 51));
        btnVenta1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/ve3.png"))); // NOI18N
        btnVenta1.setMnemonic('k');
        btnVenta1.setText("Ventas");
        btnVenta1.setContentAreaFilled(false);
        btnVenta1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVenta1.setFocusPainted(false);
        btnVenta1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVenta1.setIconTextGap(0);
        btnVenta1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/ve4.png"))); // NOI18N
        btnVenta1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnVenta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVenta1ActionPerformed(evt);
            }
        });

        lblHora.setFont(new java.awt.Font("AR CHRISTY", 3, 18)); // NOI18N
        lblHora.setForeground(new java.awt.Color(0, 102, 102));
        lblHora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/clock3.png"))); // NOI18N
        lblHora.setText("00:00:00");

        javax.swing.GroupLayout kGradientPanel2Layout = new javax.swing.GroupLayout(kGradientPanel2);
        kGradientPanel2.setLayout(kGradientPanel2Layout);
        kGradientPanel2Layout.setHorizontalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNuevo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCaja)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVenta1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblHora, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        kGradientPanel2Layout.setVerticalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnCaja, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnVenta1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHora, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo1.png"))); // NOI18N

        tbn_escritorio.setLayer(kGradientPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        tbn_escritorio.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        tbn_escritorio.setLayer(kGradientPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        tbn_escritorio.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout tbn_escritorioLayout = new javax.swing.GroupLayout(tbn_escritorio);
        tbn_escritorio.setLayout(tbn_escritorioLayout);
        tbn_escritorioLayout.setHorizontalGroup(
            tbn_escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(tbn_escritorioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 930, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(kGradientPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        tbn_escritorioLayout.setVerticalGroup(
            tbn_escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tbn_escritorioLayout.createSequentialGroup()
                .addComponent(kGradientPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(tbn_escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tbn_escritorioLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(120, 120, 120))
                    .addGroup(tbn_escritorioLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jMenuBar1.setForeground(new java.awt.Color(0, 102, 102));
        jMenuBar1.setToolTipText("");
        jMenuBar1.setAlignmentX(4.0F);
        jMenuBar1.setMaximumSize(new java.awt.Dimension(220, 32769));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(212, 35));

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/ar1.png"))); // NOI18N
        jMenu1.setText("Archivo");
        jMenu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu1.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N

        jMenuItem8.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/sa1.png"))); // NOI18N
        jMenuItem8.setText("Cerrar Sesión");
        jMenuItem8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem8);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/ce2.png"))); // NOI18N
        jMenuItem3.setText("Salir");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/reg.png"))); // NOI18N
        jMenu2.setText("Registro");
        jMenu2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu2.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/prod2.png"))); // NOI18N
        jMenuItem2.setText("Productos");
        jMenuItem2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem9.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem9.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/cli1.png"))); // NOI18N
        jMenuItem9.setText("Clientes");
        jMenuItem9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem9);

        mniEmpleado.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        mniEmpleado.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        mniEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/emp1.png"))); // NOI18N
        mniEmpleado.setText("Empleados");
        mniEmpleado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mniEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniEmpleadoActionPerformed(evt);
            }
        });
        jMenu2.add(mniEmpleado);

        mniEmpleado1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        mniEmpleado1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        mniEmpleado1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/pro1.png"))); // NOI18N
        mniEmpleado1.setText("Proveedores");
        mniEmpleado1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mniEmpleado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniEmpleado1ActionPerformed(evt);
            }
        });
        jMenu2.add(mniEmpleado1);

        jMenuItem4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/c2.png"))); // NOI18N
        jMenuItem4.setText("Presentación");
        jMenuItem4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/lab3.png"))); // NOI18N
        jMenuItem6.setText("Laboratorios");
        jMenuItem6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        mnuComprobante.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        mnuComprobante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/c1.png"))); // NOI18N
        mnuComprobante.setText("Comprobantes");
        mnuComprobante.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnuComprobante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuComprobanteActionPerformed(evt);
            }
        });
        jMenu2.add(mnuComprobante);

        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/mov.png"))); // NOI18N
        jMenu3.setText("Movimiento");
        jMenu3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu3.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N

        mnuCompra.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK));
        mnuCompra.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        mnuCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/co1.png"))); // NOI18N
        mnuCompra.setText("Compras");
        mnuCompra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnuCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCompraActionPerformed(evt);
            }
        });
        jMenu3.add(mnuCompra);

        jMenuItem19.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem19.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jMenuItem19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/vent1.png"))); // NOI18N
        jMenuItem19.setText("Ventas");
        jMenuItem19.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem19ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem19);

        jMenuItem24.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem24.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jMenuItem24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/caja1.png"))); // NOI18N
        jMenuItem24.setText("Caja");
        jMenuItem24.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem24ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem24);

        jMenuBar1.add(jMenu3);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/cons.png"))); // NOI18N
        jMenu5.setText("Consultas");
        jMenu5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu5.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N

        jMenuItem23.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jMenuItem23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/cons1.png"))); // NOI18N
        jMenuItem23.setText("Compras");
        jMenuItem23.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem23ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem23);

        jMenuItem15.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jMenuItem15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/cons2.png"))); // NOI18N
        jMenuItem15.setText("Clientes");
        jMenuItem15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem15);

        jmuEmpleados.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jmuEmpleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/cons4.png"))); // NOI18N
        jmuEmpleados.setText("Empleados");
        jmuEmpleados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jmuEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmuEmpleadosActionPerformed(evt);
            }
        });
        jMenu5.add(jmuEmpleados);

        jMenuItem16.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jMenuItem16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/cons5.png"))); // NOI18N
        jMenuItem16.setText("Productos");
        jMenuItem16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem16);

        jmuEmpleados1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jmuEmpleados1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/cons8.png"))); // NOI18N
        jmuEmpleados1.setText("Proveedores");
        jmuEmpleados1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jmuEmpleados1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmuEmpleados1ActionPerformed(evt);
            }
        });
        jMenu5.add(jmuEmpleados1);

        jMenuItem22.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jMenuItem22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/cons6.png"))); // NOI18N
        jMenuItem22.setText("Ventas");
        jMenuItem22.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem22ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem22);

        jMenuBar1.add(jMenu5);

        mniReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/rep.png"))); // NOI18N
        mniReportes.setText("Reportes");
        mniReportes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mniReportes.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N

        jMenuItem11.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jMenuItem11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/rep1.png"))); // NOI18N
        jMenuItem11.setText("Clientes");
        jMenuItem11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        mniReportes.add(jMenuItem11);

        jMenuItem12.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jMenuItem12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/rep2.png"))); // NOI18N
        jMenuItem12.setText("Productos");
        jMenuItem12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        mniReportes.add(jMenuItem12);

        jMenuItem13.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jMenuItem13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/rep4.png"))); // NOI18N
        jMenuItem13.setText("Proveedores");
        jMenuItem13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        mniReportes.add(jMenuItem13);

        jMenuItem21.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jMenuItem21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/rep3.png"))); // NOI18N
        jMenuItem21.setText("Empleados");
        jMenuItem21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem21ActionPerformed(evt);
            }
        });
        mniReportes.add(jMenuItem21);

        jMenuBar1.add(mniReportes);

        MnuAdministrador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/adm.png"))); // NOI18N
        MnuAdministrador.setText("Administrador");
        MnuAdministrador.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MnuAdministrador.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N

        jMenuItem10.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem10.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jMenuItem10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/us1.png"))); // NOI18N
        jMenuItem10.setText("Nuevo Usuario");
        jMenuItem10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        MnuAdministrador.add(jMenuItem10);

        jMenuBar1.add(MnuAdministrador);

        mnuPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/per.png"))); // NOI18N
        mnuPerfil.setText("Perfil");
        mnuPerfil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnuPerfil.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N

        mnuAdminPerfil.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_MASK));
        mnuAdminPerfil.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        mnuAdminPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/con1_1.png"))); // NOI18N
        mnuAdminPerfil.setText("Administrar Perfil");
        mnuAdminPerfil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnuAdminPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuAdminPerfilMouseClicked(evt);
            }
        });
        mnuAdminPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAdminPerfilActionPerformed(evt);
            }
        });
        mnuPerfil.add(mnuAdminPerfil);

        jMenuBar1.add(mnuPerfil);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbn_escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbn_escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        frmProductos neww = new frmProductos();
       CentrarVentanas(neww);
        frmProductos.txtIdPresentacion.setVisible(false);
        frmProductos.txtIdLaboratorio.setVisible(false);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        cerrar();
    }//GEN-LAST:event_formWindowClosing

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        frmLogin regresar = new frmLogin();
        regresar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem8ActionPerformed
    public void CentrarVentana(JInternalFrame internalFrame) {
        int x = (tbn_escritorio.getWidth() / 2) - internalFrame.getWidth() / 2;
        int y = (tbn_escritorio.getHeight() / 2) - internalFrame.getHeight() / 2;
        if (internalFrame.isShowing()) {
            internalFrame.setLocation(x, y);
        } else {
            tbn_escritorio.add(internalFrame);
            internalFrame.setLocation(x, y);
            internalFrame.show();
        }
    }        public void CentrarVentanaFactura(JInternalFrame internalFrame) {
        int x = (tbn_escritorio.getWidth() / 2) - internalFrame.getWidth() / 2;
        int y = (tbn_escritorio.getHeight() / 2) - internalFrame.getHeight() / 2;
        if (internalFrame.isShowing()) {
            internalFrame.setLocation(x, y);
        } else {
            tbn_escritorio.add(internalFrame);
            internalFrame.setLocation(x, y);
            internalFrame.show();
        }
    }
    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        frmClientes ventana = new frmClientes();
        CentrarVentanaInterna(ventana);
    }//GEN-LAST:event_jMenuItem9ActionPerformed
    //CENTRAR LA VENTANA INTERNA
    public void CentrarVentanaInterna(JInternalFrame internalFrame) {
        int x = (tbn_escritorio.getWidth() / 2) - internalFrame.getWidth() / 2;
        int y = (tbn_escritorio.getHeight() / 2) - internalFrame.getHeight() / 2;
        if (internalFrame.isShowing()) {
            internalFrame.setLocation(x, y);
        } else {
            tbn_escritorio.add(internalFrame);
            internalFrame.setLocation(x, y);
            internalFrame.show();
        }
    }
    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        frmUsuarios ventana = new frmUsuarios();
        CentrarVentanaUsuario(ventana);
                frmUsuarios.lblImagen.setVisible(false);
                frmUsuarios.txtImagen.setVisible(false);
                frmUsuarios.btnImagen.setVisible(false);
    }//GEN-LAST:event_jMenuItem10ActionPerformed
    public void CentrarVentanaUsuario(JInternalFrame internalFrame) {
        int x = (tbn_escritorio.getWidth() / 2) - internalFrame.getWidth() / 2;
        int y = (tbn_escritorio.getHeight() / 2) - internalFrame.getHeight() / 2;
        if (internalFrame.isShowing()) {
            internalFrame.setLocation(x, y);
        } else {
            tbn_escritorio.add(internalFrame);
            internalFrame.setLocation(x, y);
            internalFrame.show();
        }
    }
    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        ConsultasClientes ventanasss = new ConsultasClientes();
        CentrarVentanaConsultaCliente(ventanasss);
    }//GEN-LAST:event_jMenuItem15ActionPerformed
    public void CentrarVentanaConsultaCliente(JInternalFrame internalFrame) {
        int x = (tbn_escritorio.getWidth() / 2) - internalFrame.getWidth() / 2;
        int y = (tbn_escritorio.getHeight() / 2) - internalFrame.getHeight() / 2;
        if (internalFrame.isShowing()) {
            internalFrame.setLocation(x, y);
        } else {
            tbn_escritorio.add(internalFrame);
            internalFrame.setLocation(x, y);
            internalFrame.show();
        }
    }    
    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        ConsultasProductos ventana = new ConsultasProductos();
        CentrarVentanas(ventana);
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
         ReportesCliente reporte = new ReportesCliente();
        CentrarVentanas(reporte);   
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void mnuAdminPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAdminPerfilActionPerformed
        AdministrarPerfil ventana = new AdministrarPerfil();
        CentrarVentanas(ventana);
        
        String busqueda_Id = metodos.buscarId(frmLogin.txtUsuario.getText());
        ventana.txtId.setText(busqueda_Id);
        
        String busqueda_Dni = metodos.buscarDni(frmLogin.txtUsuario.getText());
        ventana.txtDni.setText(busqueda_Dni);
        
        String busqueda_apellidos = metodos.buscarApellidos(frmLogin.txtUsuario.getText());
        ventana.txtApellidos.setText(busqueda_apellidos);
        
        String busqueda_nombre = metodos.buscarNombre(frmLogin.txtUsuario.getText());
        ventana.txtNombres.setText(busqueda_nombre);
        
        String busqueda_Email = metodos.buscarEmail(frmLogin.txtUsuario.getText());
        ventana.txtEmail.setText(busqueda_Email);
        
        String busqueda_Usuario = metodos.buscarUsuario(frmLogin.txtUsuario.getText());
        ventana.txtNomUsuario.setText(busqueda_Usuario);
        
        String busqueda_Contraseña = metodos.buscarContraseña(frmLogin.txtUsuario.getText());
        ventana.txtClave.setText(busqueda_Contraseña);
        
        String busqueda_TipoUsuario = metodos.buscarTipoUsuario(frmLogin.txtUsuario.getText());
        ventana.txtTipoUser.setText(busqueda_TipoUsuario);
        
        String busqueda_Estado = metodos.buscarEstado(frmLogin.txtUsuario.getText());
        ventana.txtEstado.setText(busqueda_Estado);
        
        /*String busqueda_Foto = metodos.buscarFoto(frmLogin.txtUsuario.getText());
        ventana.txtImagen.setText(busqueda_Foto);*/

        int x = Integer.valueOf(lblId.getText());
        if( x == 1){
        AdministrarPerfil.jpInvitado.setVisible(false);
    }else{
            AdministrarPerfil.jpAdmin.setVisible(false);
            AdministrarPerfil.jpInvitado.setVisible(true);
        }
        
    }//GEN-LAST:event_mnuAdminPerfilActionPerformed

    private void jMenuItem22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem22ActionPerformed
       ConsultaVentas ventana = new ConsultaVentas();
        CentrarVentanas(ventana);
    }//GEN-LAST:event_jMenuItem22ActionPerformed

    private void mnuAdminPerfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuAdminPerfilMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuAdminPerfilMouseClicked

    private void mniEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniEmpleadoActionPerformed
        frmEmpleados ventana = new frmEmpleados();
        CentrarVentanas(ventana);
        
        String busqueda_Id = metodos.buscarId(frmLogin.txtUsuario.getText());
        ventana.txtIdUsuario.setText(busqueda_Id);
    }//GEN-LAST:event_mniEmpleadoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        AdministrarPerfil ventana = new AdministrarPerfil();
        CentrarVentanas(ventana);
        
        String busqueda_Id = metodos.buscarId(frmLogin.txtUsuario.getText());
        ventana.txtId.setText(busqueda_Id);
        
        String busqueda_Dni = metodos.buscarDni(frmLogin.txtUsuario.getText());
        ventana.txtDni.setText(busqueda_Dni);
        
        String busqueda_apellidos = metodos.buscarApellidos(frmLogin.txtUsuario.getText());
        ventana.txtApellidos.setText(busqueda_apellidos);
        
        String busqueda_nombre = metodos.buscarNombre(frmLogin.txtUsuario.getText());
        ventana.txtNombres.setText(busqueda_nombre);
        
        String busqueda_Email = metodos.buscarEmail(frmLogin.txtUsuario.getText());
        ventana.txtEmail.setText(busqueda_Email);
        
        String busqueda_Usuario = metodos.buscarUsuario(frmLogin.txtUsuario.getText());
        ventana.txtNomUsuario.setText(busqueda_Usuario);
        
        String busqueda_Contraseña = metodos.buscarContraseña(frmLogin.txtUsuario.getText());
        ventana.txtClave.setText(busqueda_Contraseña);
        
        String busqueda_TipoUsuario = metodos.buscarTipoUsuario(frmLogin.txtUsuario.getText());
        ventana.txtTipoUser.setText(busqueda_TipoUsuario);
        
        String busqueda_Estado = metodos.buscarEstado(frmLogin.txtUsuario.getText());
        ventana.txtEstado.setText(busqueda_Estado);
        
        /*String busqueda_Foto = metodos.buscarFoto(frmLogin.txtUsuario.getText());
        ventana.cbxPrueva.setText(busqueda_Foto);*/

        int x = Integer.valueOf(lblId.getText());
        if( x == 1){
        AdministrarPerfil.jpInvitado.setVisible(false);
    }else{
            AdministrarPerfil.jpAdmin.setVisible(false);
            AdministrarPerfil.jpInvitado.setVisible(true);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jmuEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmuEmpleadosActionPerformed
       ConsultasEmpleados ventana = new ConsultasEmpleados();
        CentrarVentanas(ventana);
    }//GEN-LAST:event_jmuEmpleadosActionPerformed

    private void jMenuItem19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem19ActionPerformed

        Ventas ventana = new Ventas();
        CentrarVentanaFactura(ventana);
        Ventas.btnNuevo.requestFocus();
        Ventas.txtCosto.setVisible(false);
        Ventas.txtIdComprobante.setVisible(false);
        String busqueda_Id = metodos.buscarId(frmLogin.txtUsuario.getText());
        ventana.txtIdEmpleado.setText(busqueda_Id);
//        frmVentas.txtCant.setVisible(false);
//        frmVentas.txtImporte.setVisible(false);
//        frmVentas.txtIgvTotal.setVisible(false);
//        frmVentas.txtSubTotal.setVisible(false);
//        frmVentas.txtTot.setVisible(false);
//        frmVentas.txtNumFactura.setVisible(false);
//        frmVentas.txtIdComprobante.setVisible(false);
//
//        frmVentas.txtIdVenta.setVisible(false);
//        frmVentas.txtCantidad.setVisible(false);
//        frmVentas.jpnVuelto.setVisible(false);

    }//GEN-LAST:event_jMenuItem19ActionPerformed

    private void mniEmpleado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniEmpleado1ActionPerformed
        frmProveedor ventana = new frmProveedor();
        CentrarVentanas(ventana);
    }//GEN-LAST:event_mniEmpleado1ActionPerformed

    private void mnuCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCompraActionPerformed
       frmCompras ventana = new frmCompras();
        CentrarVentanas(ventana);
        String busqueda_Id = metodos.buscarId(frmLogin.txtUsuario.getText());
        ventana.txtIdEmpleado.setText(busqueda_Id);
        frmCompras.txtUltimoId.setVisible(false);
        frmCompras.txtIdProveedor.setVisible(false);
    }//GEN-LAST:event_mnuCompraActionPerformed

    private void jMenuItem21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem21ActionPerformed
        ReportesEmpleados ventanasss = new ReportesEmpleados();
        CentrarVentanaConsultaCliente(ventanasss);
    }//GEN-LAST:event_jMenuItem21ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        ReportesProductos ventanasss = new ReportesProductos();
        CentrarVentanaConsultaCliente(ventanasss);
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem23ActionPerformed
        ConsultaCompras ventana = new ConsultaCompras();
        CentrarVentanas(ventana);
    }//GEN-LAST:event_jMenuItem23ActionPerformed

    private void jMenuItem24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem24ActionPerformed
         frmCaja ventana = new frmCaja();
        CentrarVentanas(ventana);
    }//GEN-LAST:event_jMenuItem24ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        AcercaDe ventana = new AcercaDe();
        CentrarVentanas(ventana);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
      cerrar();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        frmProductos neww = new frmProductos();
       CentrarVentanas(neww);
        frmProductos.txtIdPresentacion.setVisible(false);
        frmProductos.txtIdLaboratorio.setVisible(false);
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteActionPerformed
         frmClientes ventana = new frmClientes();
        CentrarVentanaInterna(ventana);
    }//GEN-LAST:event_btnClienteActionPerformed

    private void btnCajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCajaActionPerformed
       frmCaja caja = new frmCaja();
       CentrarVentanas(caja);
    }//GEN-LAST:event_btnCajaActionPerformed

    private void btnVenta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVenta1ActionPerformed
      Ventas ventana = new Ventas();
        CentrarVentanaFactura(ventana);
        Ventas.btnNuevo.requestFocus();
        Ventas.txtCosto.setVisible(false);
        Ventas.txtIdComprobante.setVisible(false);
        String busqueda_Id = metodos.buscarId(frmLogin.txtUsuario.getText());
        ventana.txtIdEmpleado.setText(busqueda_Id);
    }//GEN-LAST:event_btnVenta1ActionPerformed

    private void jmuEmpleados1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmuEmpleados1ActionPerformed
        ConsultasProveedores ventana = new ConsultasProveedores();
        CentrarVentanas(ventana);
    }//GEN-LAST:event_jmuEmpleados1ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
         ReportesProveedor ventanasss = new ReportesProveedor();
        CentrarVentanaConsultaCliente(ventanasss);
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        frmPresentacion ventana = new frmPresentacion();
        CentrarVentanas(ventana);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
       frmLaboratorio ventana = new frmLaboratorio();
        CentrarVentanas(ventana);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void mnuComprobanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuComprobanteActionPerformed
        frmComprobante ventana = new frmComprobante();
        CentrarVentanas(ventana);
    }//GEN-LAST:event_mnuComprobanteActionPerformed
    public void CentrarVentanas(JInternalFrame internalFrame) {
        int x = (tbn_escritorio.getWidth() / 2) - internalFrame.getWidth() / 2;
        int y = (tbn_escritorio.getHeight() / 2) - internalFrame.getHeight() / 2;
        if (internalFrame.isShowing()) {
            internalFrame.setLocation(x, y);
        } else {
            tbn_escritorio.add(internalFrame);
            internalFrame.setLocation(x, y);
            internalFrame.show();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JMenu MnuAdministrador;
    private javax.swing.JButton btnCaja;
    private javax.swing.JButton btnCliente;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnVenta1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton jToggleButton1;
    public static javax.swing.JMenuItem jmuEmpleados;
    public static javax.swing.JMenuItem jmuEmpleados1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel2;
    private javax.swing.JLabel lblHora;
    public javax.swing.JLabel lblId;
    public javax.swing.JLabel lblNombreUsuario;
    public javax.swing.JLabel lblRol;
    public static javax.swing.JMenuItem mniEmpleado;
    public static javax.swing.JMenuItem mniEmpleado1;
    public static javax.swing.JMenu mniReportes;
    public static javax.swing.JMenuItem mnuAdminPerfil;
    public static javax.swing.JMenuItem mnuCompra;
    public static javax.swing.JMenuItem mnuComprobante;
    public static javax.swing.JMenu mnuPerfil;
    public static javax.swing.JDesktopPane tbn_escritorio;
    // End of variables declaration//GEN-END:variables

}
