
package Vista;

import Conexion.ConexionBD;
import java.sql.*;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class ReportesEmpleados extends javax.swing.JInternalFrame {

    /** Creates new form ConsultasProductos */
    public ReportesEmpleados() {
        initComponents();
        txtDni.requestFocus();
        txtEsp.setEnabled(false);
        txtSexo.setEnabled(false);
        mostrartodosEmpleados("");
    }
   

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        rbtDni = new javax.swing.JRadioButton();
        rbtEsp = new javax.swing.JRadioButton();
        rbtSexo = new javax.swing.JRadioButton();
        rbtTotal = new javax.swing.JRadioButton();
        btnGenerar = new javax.swing.JButton();
        txtDni = new jtextfieldround.JTextFieldRound();
        txtEsp = new jtextfieldround.JTextFieldRound();
        txtSexo = new jtextfieldround.JTextFieldRound();
        jLabel1 = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();
        txtCantidad = new jtextfieldround.JTextFieldRound();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbEmpleado = new rojerusan.RSTableMetro();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setTitle("Reportes de Empleados");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Reportes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 11), new java.awt.Color(0, 102, 102))); // NOI18N

        buttonGroup1.add(rbtDni);
        rbtDni.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rbtDni.setForeground(new java.awt.Color(0, 102, 102));
        rbtDni.setSelected(true);
        rbtDni.setText("Generar Reporte por Dni:");
        rbtDni.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rbtDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtDniActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtEsp);
        rbtEsp.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rbtEsp.setForeground(new java.awt.Color(0, 102, 102));
        rbtEsp.setText("Generar Reporte por Especialidad:");
        rbtEsp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rbtEsp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtEspActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtSexo);
        rbtSexo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rbtSexo.setForeground(new java.awt.Color(0, 102, 102));
        rbtSexo.setText("Generar Reporte por Sexo:");
        rbtSexo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rbtSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtSexoActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtTotal);
        rbtTotal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rbtTotal.setForeground(new java.awt.Color(0, 102, 102));
        rbtTotal.setText("Mostrar Reporte General");
        rbtTotal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rbtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtTotalActionPerformed(evt);
            }
        });

        btnGenerar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnGenerar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/print_1.png"))); // NOI18N
        btnGenerar.setText("Imprimir");
        btnGenerar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGenerar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGenerar.setIconTextGap(0);
        btnGenerar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });

        txtDni.setCaretColor(new java.awt.Color(0, 102, 0));
        txtDni.setForeground(new java.awt.Color(0, 51, 51));
        txtDni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDniKeyTyped(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDniKeyReleased(evt);
            }
        });

        txtEsp.setCaretColor(new java.awt.Color(0, 102, 0));
        txtEsp.setForeground(new java.awt.Color(0, 51, 51));
        txtEsp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEspKeyReleased(evt);
            }
        });

        txtSexo.setCaretColor(new java.awt.Color(0, 102, 0));
        txtSexo.setForeground(new java.awt.Color(0, 51, 51));
        txtSexo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSexoKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbtDni)
                    .addComponent(rbtEsp)
                    .addComponent(rbtSexo)
                    .addComponent(rbtTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEsp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(87, 87, 87)
                .addComponent(btnGenerar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbtDni)
                            .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbtEsp)
                            .addComponent(txtEsp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbtSexo)
                            .addComponent(txtSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addComponent(rbtTotal))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(btnGenerar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Cantidad de Registros:");

        btnCerrar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/can12.png"))); // NOI18N
        btnCerrar.setText("Volver");
        btnCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCerrar.setIconTextGap(0);
        btnCerrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        txtCantidad.setEditable(false);

        tbEmpleado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbEmpleado.setAltoHead(22);
        tbEmpleado.setColorBackgoundHead(new java.awt.Color(0, 51, 51));
        tbEmpleado.setColorFilasBackgound2(new java.awt.Color(240, 240, 240));
        tbEmpleado.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        tbEmpleado.setColorFilasForeground2(new java.awt.Color(0, 0, 0));
        tbEmpleado.setFuenteFilas(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        tbEmpleado.setFuenteFilasSelect(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tbEmpleado.setFuenteHead(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        tbEmpleado.setGrosorBordeFilas(0);
        tbEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbEmpleadoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbEmpleado);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(280, 280, 280)
                        .addComponent(btnCerrar))
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnCerrar)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(22, 22, 22))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void rbtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtTotalActionPerformed
// TODO add your handling code here:
    if(rbtTotal.isSelected()==true)
    {
        txtDni.setEnabled(false);
        txtDni.setText("");
        txtEsp.setEnabled(false);
        txtEsp.setText("");
        txtSexo.setEnabled(false);
        txtSexo.setText("");
        mostrartodosEmpleados("");
    }
   
}//GEN-LAST:event_rbtTotalActionPerformed

private void rbtDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtDniActionPerformed
// TODO add your handling code here:
    if(rbtDni.isSelected()==true)
    {
        txtDni.setEnabled(true);
        txtDni.setText("");
        txtEsp.setEnabled(false);
        txtEsp.setText("");
        txtSexo.setEnabled(false);
        txtSexo.setText("");
        btnGenerar.setEnabled(true);
        txtDni.requestFocus();
        mostrartodosEmpleados("");
    }
}//GEN-LAST:event_rbtDniActionPerformed

    private void rbtEspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtEspActionPerformed
        if(rbtEsp.isSelected()==true)
    {
        txtEsp.setEnabled(true);
        txtEsp.setText("");
        txtDni.setEnabled(false);
        txtSexo.setEnabled(false);
        txtDni.setText("");
        txtSexo.setText("");
        btnGenerar.setEnabled(true);
        txtEsp.requestFocus();
        mostrartodosEmpleados("");
    }
    }//GEN-LAST:event_rbtEspActionPerformed

    private void rbtSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtSexoActionPerformed
         if(rbtSexo.isSelected()==true)
    {
        txtSexo.setEnabled(true);
        txtSexo.setText("");
        txtDni.setEnabled(false);
        txtDni.setText("");
        txtEsp.setEnabled(false);
        txtEsp.setText("");
        btnGenerar.setEnabled(true);
        txtSexo.requestFocus();
        mostrartodosEmpleados("");
    }
    }//GEN-LAST:event_rbtSexoActionPerformed

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
        
         JRReporte cr = new JRReporte();
         Connection con = null;
    
    if(rbtDni.isSelected()==true)
    {
        if (txtDni.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "por favor complete el campo vacío");
            txtDni.requestFocus();
            //--------------------------------------------------
        } else {
            try {
                con = ConexionBD.conectar();
                Map parametros = new HashMap();
                parametros.put("Dni", txtDni.getText());
                String ruta = System.getProperty("user.dir") + "\\src\\Reportes\\Employes.jrxml";
                cr.abrirReporte(ruta, con, parametros);
                con.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error al cargar el reporte de Empleados", "ERROR", JOptionPane.ERROR_MESSAGE);

            }
        }   
    }
    if(rbtTotal.isSelected()==true)
    {
            try {
                con = ConexionBD.conectar();
                String ruta = System.getProperty("user.dir") + "\\src\\Reportes\\Empleado.jrxml"; 
                cr.abrirReporte(ruta, con);
                con.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error al cargar el reporte de Empleados", "ERROR", JOptionPane.ERROR_MESSAGE);

            }
        
    }
    if(rbtEsp.isSelected()==true)
    {
        if (txtEsp.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "por favor complete el campo vacío");
            txtEsp.requestFocus();
            //--------------------------------------------------
        } else {
            try {
                con = ConexionBD.conectar();
                Map parametros = new HashMap();
                parametros.put("Especialidad", txtEsp.getText());
                String ruta = System.getProperty("user.dir") + "\\src\\Reportes\\EmpEsp.jrxml";
                cr.abrirReporte(ruta, con, parametros);
                con.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error al cargar el reporte de Empleados", "ERROR", JOptionPane.ERROR_MESSAGE);

            }
        }
    }
    if(rbtSexo.isSelected()==true)
    {
        if (txtSexo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "por favor complete el campo vacío");
            txtSexo.requestFocus();
            //--------------------------------------------------
        } else {
            try {
                con = ConexionBD.conectar();
                Map parametros = new HashMap();
                parametros.put("Sexo", txtSexo.getText());
                String ruta = System.getProperty("user.dir") + "\\src\\Reportes\\EmpSexo.jrxml";
                cr.abrirReporte(ruta, con, parametros);
                con.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error al cargar el reporte de Empleados", "ERROR", JOptionPane.ERROR_MESSAGE);

            }
        }
    }
    }//GEN-LAST:event_btnGenerarActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void txtDniKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDniKeyReleased
        mostrartodosEmpleados(txtDni.getText());
        
    }//GEN-LAST:event_txtDniKeyReleased

    private void txtDniKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDniKeyTyped
     char car = evt.getKeyChar();
        if ((car < '0' || car > '9')) {
            evt.consume();
        }
        int i = txtDni.getText().length();
        if (txtDni.getText().trim().length() < 8) {

        } else {
            i = 10;
            String com = txtDni.getText().substring(0, 7);
            txtDni.setText("");
            txtDni.setText(com);
        }
    }//GEN-LAST:event_txtDniKeyTyped

    private void txtEspKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEspKeyReleased
       mostrartodosEmpleados(txtEsp.getText());
    }//GEN-LAST:event_txtEspKeyReleased

    private void txtSexoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSexoKeyReleased
         mostrartodosEmpleados(txtSexo.getText());
    }//GEN-LAST:event_txtSexoKeyReleased

    private void tbEmpleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbEmpleadoMouseClicked
       int row = tbEmpleado.getSelectedRow();
        txtDni.setText(tbEmpleado.getValueAt(row, 5).toString());
        txtEsp.setText(tbEmpleado.getValueAt(row, 3).toString());
        txtSexo.setText(tbEmpleado.getValueAt(row, 4).toString());
    }//GEN-LAST:event_tbEmpleadoMouseClicked

    
     void mostrartodosEmpleados(String Buscar)
    {
        DefaultTableModel tabla= new DefaultTableModel();
        String []titulos={"Id","Nombres","Apellidos","Especialidad","Sexo","DNI","Email","Teléfono","Dirección","Ingreso","Salida","Sueldo"};
        tabla.setColumnIdentifiers(titulos);
        this.tbEmpleado.setModel(tabla);
        String consulta= "SELECT * FROM empleado WHERE CONCAT(Dni, Especialidad, Sexo) LIKE '%" + Buscar + "%'";
        String []Datos= new String [12];
        try {
            Statement st = cn.createStatement();
            ResultSet rs= st.executeQuery(consulta);
            while(rs.next())
            {
                Datos[0]=rs.getString("IdEmpleado");
                Datos[1]=rs.getString("Nombres");
                Datos[2]=rs.getString("Apellidos");
                Datos[3]=rs.getString("Especialidad");
                Datos[4]=rs.getString("Sexo");
                Datos[5]=rs.getString("Dni");
                Datos[6]=rs.getString("Email");
                Datos[7]=rs.getString("Telefono");
                Datos[8]=rs.getString("Direccion");
                Datos[9]=rs.getString("HoraIngreso");
                Datos[10]=rs.getString("HoraSalida");
                Datos[11]=rs.getString("Sueldo");
                tabla.addRow(Datos);
            }
             tbEmpleado.setModel(tabla);
            txtCantidad.setText(""+tbEmpleado.getRowCount());
        } catch (SQLException ex) {
            Logger.getLogger(ReportesEmpleados.class.getName()).log(Level.SEVERE, null, ex);
        }          
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnGenerar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rbtDni;
    private javax.swing.JRadioButton rbtEsp;
    private javax.swing.JRadioButton rbtSexo;
    private javax.swing.JRadioButton rbtTotal;
    private rojerusan.RSTableMetro tbEmpleado;
    private jtextfieldround.JTextFieldRound txtCantidad;
    private jtextfieldround.JTextFieldRound txtDni;
    private jtextfieldround.JTextFieldRound txtEsp;
    private jtextfieldround.JTextFieldRound txtSexo;
    // End of variables declaration//GEN-END:variables
ConexionBD cc= new ConexionBD();
Connection cn = cc.conectar();

}
