
package Vista;

import Conexion.ConexionBD;
import Metodos.Metodos_Productos;
import java.sql.*;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;

public class ReportesProductos extends javax.swing.JInternalFrame {

    private final Metodos_Productos CP = new Metodos_Productos();
    /** Creates new form ConsultasProductos */
    public ReportesProductos() {
        initComponents();
        txtCategoria.requestFocus();
        txtId.setEnabled(false);
        txtEstado.setEnabled(false);
        listar();
    }
   private void listar() {
        tbProductos.setModel(CP.getDatos());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        rbtCategoria = new javax.swing.JRadioButton();
        rbtId = new javax.swing.JRadioButton();
        rbtEstado = new javax.swing.JRadioButton();
        rbtTotal = new javax.swing.JRadioButton();
        txtCategoria = new jtextfieldround.JTextFieldRound();
        txtId = new jtextfieldround.JTextFieldRound();
        txtEstado = new jtextfieldround.JTextFieldRound();
        btnGenerar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbProductos = new rojerusan.RSTableMetro();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setTitle("Reportes de Productos");

        jPanel1.setBackground(new java.awt.Color(251, 248, 248));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Reportes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 11), new java.awt.Color(0, 102, 102))); // NOI18N

        buttonGroup1.add(rbtCategoria);
        rbtCategoria.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rbtCategoria.setForeground(new java.awt.Color(0, 102, 102));
        rbtCategoria.setSelected(true);
        rbtCategoria.setText("Generar Reporte por Presentación:");
        rbtCategoria.setContentAreaFilled(false);
        rbtCategoria.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rbtCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtCategoriaActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtId);
        rbtId.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rbtId.setForeground(new java.awt.Color(0, 102, 102));
        rbtId.setText("Generar Reporte por Id:");
        rbtId.setContentAreaFilled(false);
        rbtId.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rbtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtIdActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtEstado);
        rbtEstado.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rbtEstado.setForeground(new java.awt.Color(0, 102, 102));
        rbtEstado.setText("Generar Reporte por Estado:");
        rbtEstado.setContentAreaFilled(false);
        rbtEstado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rbtEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtEstadoActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtTotal);
        rbtTotal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rbtTotal.setForeground(new java.awt.Color(0, 102, 102));
        rbtTotal.setText("Mostrar Reporte General");
        rbtTotal.setContentAreaFilled(false);
        rbtTotal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rbtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtTotalActionPerformed(evt);
            }
        });

        txtCategoria.setCaretColor(new java.awt.Color(0, 102, 153));
        txtCategoria.setForeground(new java.awt.Color(0, 51, 153));

        txtId.setForeground(new java.awt.Color(0, 51, 153));
        txtId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdKeyTyped(evt);
            }
        });

        txtEstado.setForeground(new java.awt.Color(0, 51, 153));

        btnGenerar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnGenerar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/print_1.png"))); // NOI18N
        btnGenerar.setText("Generar");
        btnGenerar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGenerar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGenerar.setIconTextGap(0);
        btnGenerar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rbtTotal)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rbtCategoria)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbtEstado)
                            .addComponent(rbtId))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                .addComponent(btnGenerar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(147, 147, 147))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbtCategoria)
                            .addComponent(txtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbtId)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbtEstado)
                            .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(btnGenerar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14)
                .addComponent(rbtTotal)
                .addGap(9, 9, 9))
        );

        btnCerrar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/can12.png"))); // NOI18N
        btnCerrar.setText("Volver");
        btnCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCerrar.setIconTextGap(0);
        btnCerrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        tbProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbProductos.setAltoHead(22);
        tbProductos.setColorBackgoundHead(new java.awt.Color(0, 51, 51));
        tbProductos.setColorFilasBackgound2(new java.awt.Color(240, 240, 240));
        tbProductos.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        tbProductos.setColorFilasForeground2(new java.awt.Color(0, 0, 0));
        tbProductos.setFuenteFilas(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        tbProductos.setFuenteFilasSelect(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tbProductos.setFuenteHead(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        tbProductos.setGrosorBordeFilas(0);
        tbProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbProductosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbProductos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCerrar))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCerrar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void rbtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtTotalActionPerformed
// TODO add your handling code here:
    if(rbtTotal.isSelected()==true)
    {
        txtCategoria.setEnabled(false);
        txtCategoria.setText("");
        txtId.setEnabled(false);
        txtId.setText("");
        txtEstado.setEnabled(false);
        txtEstado.setText("");
        listar();
    }
   
}//GEN-LAST:event_rbtTotalActionPerformed

private void rbtCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtCategoriaActionPerformed
// TODO add your handling code here:
    if(rbtCategoria.isSelected()==true)
    {
        txtCategoria.setEnabled(true);
        txtCategoria.setText("");
        txtId.setEnabled(false);
        txtId.setText("");
        txtEstado.setEnabled(false);
        txtEstado.setText("");
        btnGenerar.setEnabled(true);
        txtCategoria.requestFocus();
         listar();
    }
}//GEN-LAST:event_rbtCategoriaActionPerformed

    private void rbtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtIdActionPerformed
        if(rbtId.isSelected()==true)
    {
        txtId.setEnabled(true);
        txtId.setText("");
        txtCategoria.setEnabled(false);
        txtEstado.setEnabled(false);
        txtCategoria.setText("");
        txtEstado.setText("");
        btnGenerar.setEnabled(true);
        txtId.requestFocus();
        listar();
    }
    }//GEN-LAST:event_rbtIdActionPerformed

    private void rbtEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtEstadoActionPerformed
         if(rbtEstado.isSelected()==true)
    {
        txtEstado.setEnabled(true);
        txtEstado.setText("");
        txtCategoria.setEnabled(false);
        txtCategoria.setText("");
        txtId.setEnabled(false);
        txtId.setText("");
        btnGenerar.setEnabled(true);
        txtEstado.requestFocus();
        listar();
    }
    }//GEN-LAST:event_rbtEstadoActionPerformed

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
        
         JRReporte cr = new JRReporte();
         Connection con = null;
    
    if(rbtCategoria.isSelected()==true)
    {
        if (txtCategoria.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "por favor complete el campo vacío");
            txtCategoria.requestFocus();
            //--------------------------------------------------
        } else {
            try {
                con = ConexionBD.conectar();
                Map parametros = new HashMap();
                parametros.put("Categoria", txtCategoria.getText());
                String ruta = System.getProperty("user.dir") + "\\src\\Reportes\\ProdCat.jrxml";
                cr.abrirReporte(ruta, con, parametros);
                con.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error al cargar el reporte de Empleados", "ERROR", JOptionPane.ERROR_MESSAGE);

            }
        }   
    }
    if(rbtTotal.isSelected()==true)
    {
            try {
                con = ConexionBD.conectar();
                String ruta = System.getProperty("user.dir") + "\\src\\Reportes\\Productos.jrxml"; 
                cr.abrirReporte(ruta, con);
                con.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error al cargar el reporte de Empleados", "ERROR", JOptionPane.ERROR_MESSAGE);

            }
        
    }
    if(rbtId.isSelected()==true)
    {
        if (txtId.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "por favor complete el campo vacío");
            txtId.requestFocus();
            //--------------------------------------------------
        } else {
            try {
                con = ConexionBD.conectar();
                Map parametros = new HashMap();
                parametros.put("ID", txtId.getText());
                String ruta = System.getProperty("user.dir") + "\\src\\Reportes\\ProID.jrxml";
                cr.abrirReporte(ruta, con, parametros);
                con.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error al cargar el reporte de Empleados", "ERROR", JOptionPane.ERROR_MESSAGE);

            }
        }
    }
    if(rbtEstado.isSelected()==true)
    {
        if (txtEstado.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "por favor complete el campo vacío");
            txtEstado.requestFocus();
            //--------------------------------------------------
        } else {
            try {
                con = ConexionBD.conectar();
                Map parametros = new HashMap();
                parametros.put("Estado", txtEstado.getText());
                String ruta = System.getProperty("user.dir") + "\\src\\Reportes\\ProdEstado.jrxml";
                cr.abrirReporte(ruta, con, parametros);
                con.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error al cargar el reporte de Empleados", "ERROR", JOptionPane.ERROR_MESSAGE);

            }
        }
    }
    }//GEN-LAST:event_btnGenerarActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void txtIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdKeyTyped
       char car = evt.getKeyChar();
        if ((car < '0' || car > '9')) {
            evt.consume();
        }
        
    }//GEN-LAST:event_txtIdKeyTyped

    private void tbProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbProductosMouseClicked
       int row = tbProductos.getSelectedRow();
        txtCategoria.setText(tbProductos.getValueAt(row, 1).toString());
        txtId.setText(tbProductos.getValueAt(row, 0).toString());
        txtEstado.setText(tbProductos.getValueAt(row, 10).toString());
    }//GEN-LAST:event_tbProductosMouseClicked

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnGenerar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rbtCategoria;
    private javax.swing.JRadioButton rbtEstado;
    private javax.swing.JRadioButton rbtId;
    private javax.swing.JRadioButton rbtTotal;
    private rojerusan.RSTableMetro tbProductos;
    private jtextfieldround.JTextFieldRound txtCategoria;
    private jtextfieldround.JTextFieldRound txtEstado;
    private jtextfieldround.JTextFieldRound txtId;
    // End of variables declaration//GEN-END:variables
ConexionBD cc= new ConexionBD();
Connection cn = cc.conectar();

}
